version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_xdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: silverstripe
       MYSQL_USER: silverstripe
       MYSQL_PASSWORD: 123456a@

   silverstripe:
     image: holao09/silverstripe-web:latest
     restart: always
     environment:
       SS_DATABASE_SERVER: db:3306
       SS_DATABASE_USERNAME: silverstripe
       SS_DATABASE_PASSWORD: 123456a@
       VIRTUAL_HOST: ${HOSTNAME}
       LETSENCRYPT_HOST: ${HOSTNAME}
       VIRTUAL_PORT: ${PORT}
       LETSENCRYPT_EMAIL: ${EMAIL}

volumes:
    db_xdata:
networks:
  default:
    external:
      name: nginxsslproxy_default
